version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 78e4514ab548bdeb0a8a8ea8b4ab451afc1ee89e63b54244cbd92d587b48b776
    docker:
      - image: circleci/node:10.1
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
    steps:
      - checkout
      - restore_cache:
          name: Restore npm cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint code
          command: npm run lint
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npm run test:cov
      - run:
          name: "Run e2e test"
          command: npm run test:e2e
      - run:
          name: Setup and run Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            cp -r src/coverage/ ./
            ./cc-test-reporter before-build
            ./cc-test-reporter after-build
